Fix external ncbi link
broadinstitute/gnomad-browser pull request #1043
Opened 2022-11-22 17:03 UTC by rileyhgrant

Resolves #1032 

At some point, the url convention for ncbi's dbSNP changed, causing gnomAD's links to dbSNP's variants by rsID to be broken links. This is a straightforward PR the changes instances in which this resource is linked to (`ReferenceList` and `MitochondrialVariantReferenceList`) to use the correct URL.

It also DRYs up the links a bit, and adds very small scoped unit tests. 

---

Unrelated, in looking at all these components that use `<Link>` and `<ExternalLink>` that have related `ts` errors, I will likely make an issue to take a look at those (part of `gnomad-browser-toolkit`) to fix those errors so we can remove a whole slew of `ts-expects`.

2022-11-28 15:35 UTC, phildarnowsky-broad requested changes
Looks fine to me except for one small style note, `ncbiReference` and `clinvarReference` are React components, so should be capitalized, `NcbiReference` and `ClinvarReference` respectively.

2022-11-29 15:12 UTC, mattsolo1 commented
@phildarnowsky-broad for very minor changes like those requested here (capitalization, etc), does it make sense to approve the PR under the assumption they will be an easy fix (rather than going through the whole request changes/approval cycle again)?

2022-11-29 15:17 UTC, phildarnowsky-broad approved these changes

2022-11-29 15:17 UTC, phildarnowsky-broad commented
@mattsolo1 yes good call on that

2022-11-29 15:22 UTC, phildarnowsky-broad commented
@mattsolo1 one thing about that though, we'd still need an approval to merge, so if we wanted to do as you suggest we'd have to approve but with a note saying "please do X before merging". Not a problem except for the possibility of prematurely merging before you actually do X, so that's something we'd have to be careful about.

2022-11-29 16:16 UTC, rileyhgrant commented
Makes sense to me too on giving approval with minor stipulations (the caps here) going forward.
 
Thanks all!

2022-11-29 16:17 UTC, merged