Add prominent link to Gene from Variant page
broadinstitute/gnomad-browser pull request #1052
Opened 2022-12-01 15:13 UTC by rileyhgrant

Resolves #1025 

Adds a more prominent link to the Gene page from the Variant page.

![Screen Shot 2022-12-01 at 10 11 45](https://user-images.githubusercontent.com/59549713/205088697-4e6d865a-3be2-4d40-b247-e3cd5871eee7.jpg)

Uses the ENSGID from the canonical transcript for a given gene.

2022-12-01 15:27 UTC, mattsolo1 commented
When variant is found in multiple genes, should make plural (i.e. "Variant Found in Genes").

Example: http://localhost:8008/variant/9-38577187-G-A?dataset=gnomad_r2_1

(note this gene not greatest example b/c it has same gene name but with different gene ids, but you get the idea)

![image](https://user-images.githubusercontent.com/8867295/205091867-71b14a7b-8677-4c46-a950-44c14a3d0a09.png)

2022-12-01 15:28 UTC, mattsolo1 commented
When you think it is ready, can you post a screenshot on slack to Heidi as well since she requested this feature?

2022-12-01 17:13 UTC, rileyhgrant commented
Amazing - thanks for the feedback and on the example of the variant with multiple different associated ENSG IDs for canonical transcripts. Worth it to include ENSG ID in parentheses? 

I didn't realize that there could be multiple ENSG IDs associated with a single gene symbol.

2022-12-01 17:46 UTC, mattsolo1 commented
It's the first example I've seen with identical gene symbols (and the only example I could easily find using Slack search). I think this is rare enough scenario that we don't need the ENSG in parentheses, unless others ask for it.

2023-01-31 14:30 UTC, rileyhgrant commented
Per comments from the Roadmapping Meeting on Jan 17, 2023, here are a few possible solutions.

I'm a bit partial to Anne's suggestion of having a link to the Gene come before the (SNV, Insertion, etc). 

As I understand it, the idea is to at a glance get a sense of what Gene this Variant occurs in, if it's that simple. If the variant is part of the small number that occur in more than one Gene, than we can remove the Gene on the header (and maybe suggest users go further down the page if there's room to say that). 

Here are a couple screenshots of possible locations the Gene symbol could occur. I welcome any and all feedback, as this has turned into a more discussion provoking request than I thought at first. Any thoughts?




---
All these are shown in the simplest case (Variant occurs cleanly only in a single Gene, decided by the single canonical transcript).

Gene symbol before the Variant information 
![Screenshot 2023-01-31 at 09 14 44](https://user-images.githubusercontent.com/59549713/215784308-10b0e7f0-2d36-42fe-8849-f6743d4304aa.jpg)


Gene symbol after the Variant information
![Screenshot 2023-01-31 at 08 46 07](https://user-images.githubusercontent.com/59549713/215784649-55e1210f-f179-4cbb-806b-19fa8a526987.jpg)


Gene symbol after (or could be before) the 'Copy Variant ID' button.
![Screenshot 2023-01-31 at 08 47 57](https://user-images.githubusercontent.com/59549713/215784764-38b77ebe-a8b0-4aa1-b9fa-615c0abd0414.jpg)

---

The last screenshot additionally has a temporary placeholder unicode arrow. Part of this issue is that Gene links often direct to external resources, which makes some users shy away from clicking Gene links. Is there some icon or styling that we can apply to intuitively suggest that certain links are internal? Maybe if we make a SVG Favicon that's simple and recognizable, this SVG could come after/before internal links? Just a thought.

@phildarnowsky @mattsolo1 - opinions are encouraged. I'd feel good about having another set of eyes/thoughts from the team before going back into the thread in the gnomad browser channel for another round of comments.

2023-02-03 17:38 UTC, phildarnowsky-broad commented
Looking at the screenshots you have here, I think the first, with the gene symbol leading, is my preference.

There definitely are some idiomatic icons that suggest an internal link, not sure what they're called but imagine a diagonal arrow coming out of a square...I see that often. Do we have a preferred way to add small icons like that @mattsolo1 ?

2023-02-03 17:44 UTC, phildarnowsky-broad requested changes
couple very small changes requested

2023-02-03 17:44 UTC, phildarnowsky-broad commented on browser/src/VariantPage/VariantPage.tsx
> +    transcript_consequences?: TranscriptConsequence[]
@rileyhgrant GraphQL actually returns `null` not `undefined` for missing values like this, so `transcript_consequences: TranscriptConsequence[] | null` is what you want here, assuming that it is valid to be missing `transcript_consequences`.

2023-02-03 17:44 UTC, phildarnowsky-broad commented on browser/src/VariantPage/VariantPage.tsx
> +const checkGeneLink = (variant: any) => {
let's put some proper types rather than `any` for this and `transcript` below.

2023-02-03 17:44 UTC, phildarnowsky-broad commented on browser/src/VariantPage/VariantPage.tsx
> +                    <GeneLink to={`/gene/${gene.ensembleId}`}>{`⬉ ${gene.symbol}`}</GeneLink>
ah OK the icon here is similar to the one I had in mind meaning "external link"

2023-02-03 17:44 UTC, phildarnowsky-broad commented on browser/src/VariantPage/VariantPageTitle.tsx
> +      {/* <span>{','}</span>
this can come out

2023-02-03 18:43 UTC, mattsolo1 commented
Can't say I'm a huge fan of the link. How about making it a button? This makes it stylistically consistent with the surrounding buttons.

![image](https://user-images.githubusercontent.com/8867295/216682183-6daf248e-06fa-4e99-854e-bf8e97d4628d.png)

2023-02-03 20:04 UTC, rileyhgrant commented
That's fair @mattsolo1. Though, a button's extra margins become problematic on Single Nucleotide Variants and multi base insertions.

![Screenshot 2023-02-03 at 14 11 42](https://user-images.githubusercontent.com/59549713/216687388-e7ed86ed-beff-4f87-86ea-1eca3d63a56a.jpg)

Is the whole fully spelled out SNV text necessary? Or could we move to a 'SNV' with a hover text that's the full thing. I'd imagine anyone browsing gnomAD variant pages probably knows what an SNV is. 

It seems the behavior of adding an ellipses to multi base insertions or deletions that are too long exists as an edge case, but that doesn't seem like the thing to do for every single SNV.


Just Gene symbol gets it short enough to do elipses
![Screenshot 2023-02-03 at 14 21 59](https://user-images.githubusercontent.com/59549713/216698883-305de161-fc7c-4088-9ddd-1c482fa608d2.jpg)


Sample multi base insertion with elipses on prod:
![Screenshot 2023-02-03 at 15 03 28](https://user-images.githubusercontent.com/59549713/216699520-95268767-3b52-4936-bf91-2f94463d2d04.jpg)

2023-02-03 20:40 UTC, mattsolo1 commented
I don't think it's advisable to truncate SNVs ids with ellipses. I do think we could make a case for the SNV abbreviation w/ hover to see the full thing.

2023-02-03 20:41 UTC, phildarnowsky-broad commented
> I don't think it's advisable to truncate SNVs ids with ellipses. 

I concur--this is a place where small details matter a lot and shouldn't be glossed over.

2023-02-08 13:29 UTC, mattsolo1 commented
Heidi says we can definitely shorten to SNV, and that button should say "Go to gene page" or maybe we can get away with just "Gene page". The word "page" being important so that people don't think it is an external resource being linked to. Will that work?

2023-02-08 15:50 UTC, rileyhgrant commented
> Heidi says we can ...

Yep that all makes sense - thanks for checking on that and following up!

2023-02-15 20:30 UTC, phildarnowsky-broad approved these changes

2023-04-07 13:19 UTC, merged