Combine deployment docs into one main doc
broadinstitute/gnomad-browser pull request #1190
Opened 2023-09-25 20:18 UTC by elissa-alarmani

In efforts to keep up with our documenting, we are moving towards having one main markdown file detailing all the documentation for deploying the gnomad browser (with addition to the blogs and reads). Right now this is combining `NewDeployment.md` `UpdateDeployment.md`  and `NewDemoDeployment.md` into `Deployment.md`

2023-09-26 21:51 UTC, rileyhgrant reviewed
Since these are docs, I'm going to leave a comment that I'd like you to review my edits and see if you agree/disagree with them. Adding commits to this seemed an easier way of communicating, as opposed to leaving many individual comments on specific lines of an `.md` file.

Let me know your thoughts on the changes!

2023-09-27 15:11 UTC, elissa-alarmani commented
I agree with all of your changes, especially the blue/green deployment explanation, I wasn't exactly sure how to explain that since it was not in the original docs so I appreciate how you went about it. I'll convert this draft into a PR

2023-10-02 18:37 UTC, mattsolo1 requested changes

2023-10-02 18:37 UTC, mattsolo1 commented on deploy/docs/Deployment.md
> +The setup step installs the [Elastic Cloud on Kubernetes (ECK)](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-overview.html) operator.
Which setup step?

2023-10-04 16:08 UTC, elissa-alarmani commented
Apologies for the previous commits where I removed the ES docs`ElasticsearchConnection.md` and `ElasticsearchIndexAliases.md`, I misunderstood the purpose of keeping those docs separate from the deployment docs

2023-10-06 16:23 UTC, mattsolo1 approved these changes

2023-10-06 18:35 UTC, merged